version: "3.8"
services:
  api:
    build: .
    image: telemetry-pipeline:api
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP=broker:9092
    depends_on:
      - broker

  consumer:
    build: .
    image: telemetry-pipeline:consumer
    command: ["python", "src/consumer/consumer.py"]
    environment:
      - KAFKA_BOOTSTRAP=broker:9092
    depends_on:
      - broker

  # Basic Kafka stack for local dev (Confluent quickstart)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.5
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
