apiVersion: v1
kind: Service
metadata:
  name: telemetry-api
  namespace: telemetry
spec:
  selector:
    app: telemetry-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
