apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api
  namespace: telemetry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-api
  template:
    metadata:
      labels:
        app: telemetry-api
    spec:
      containers:
        - name: api
          image: telemetry-pipeline:api
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BOOTSTRAP
              value: "your-kafka:9092"
